### ISSUE TITLE
Pause player when navigating to a different route

### ISSUE THREAD

**Issue by micsan13br** [brianegan/chewie#179]
Is it possible to pause the player when changing to a different route?

widget.dispose() will be triggered for example with

- WillPopScope.onWillPop // android back button
- Navigator.pop(context); // this is fired pressing the "back" IconButton in iOS

**but not when using**

- Navigator.pushNamed(context, route); // for example when navigating to a new route using the drawer menu

Otherwise the audio will keep playing and even overlap with another audio if another video plays.

**Comment by d-apps** [comment]
The solution I found was pausing the video then disposing the controller inside the dispose. For me it's ok because I don't need the controller anymore, when I open the page again the controller is created again.

```
VideoPlayerController videoPlayerController;

  @override
  void dispose() {

    videoPlayerController.pause();
    videoPlayerController.dispose();

    print("DISPOSE CONTROLLER...");

    super.dispose();
  }
```

**Comment by micsan13br** [comment]
When popping and pushing routes, dispose() isn't used because those routes are still in the stack.
I ended up using
https://api.flutter.dev/flutter/widgets/Navigator/pushReplacementNamed.html

**Comment by cbenhagen** [comment]
I don't think there is much to do on our side. The logic of when to pause/dispose a VideoPlayerController has to be in your app. You could just pause the controller before you push the route or dispose it if you don't need it anymore. I am closing this issue. Please comment if you think there is something we can improve in Chewie.

**Comment by Babwenbiber** [comment]
So I ended up wrapping the Player Widget with a VisibilityDetector.
And if the Widget is not visible anymore, I stop the player.
For that I pass a parameter `play` to the player widget. Then in the player widget I pause (or play when visible) the player.
```
@override
  void didUpdateWidget(CustomVideoPlayer oldWidget) {
    if (oldWidget.play != widget.play) {
      if (widget.play) {
        _chewieController?.play();
        _chewieController?.setLooping(true);
        setVolume();
      } else {
        _chewieController?.pause();
      }
    }
    super.didUpdateWidget(oldWidget);
  }
```
I think it would be nice if the chewiePlayer had something like that integrated, such that one can chose to pause when the player is not seen or handle it manually.
Or at least give it as an example for the usage.
I personally needed to implement it manually anyways, because I have a scrollable feed with photos and videos and have to determine which post the user watches currently.
Let me know what you think of that feature.
