### ISSUE TITLE
crash after change some video

### ISSUE THREAD

**Issue by nitneuq33** [brianegan/chewie#181]
Hello I have crash of player when I call multiple time ChewieController, I need to change path of my local video and reload player, but after some reload ( between 4 and 10 )  player crash

**Comment by cbenhagen** [comment]
Do you dispose the ChewieController and/or the VideoPlayerController before you create the new Player? Can you provide a non-working example?

**Comment by PreviousTlx** [comment]
> Do you dispose the ChewieController and/or the VideoPlayerController before you create the new Player? Can you provide a non-working example?

I have the same problem
code like that:
if (mounted) {
setState(() {
if (widget._videoPlayerController != null) {
//widget._videoPlayerController.removeListener(videoListener);
widget._videoPlayerController.dispose();
}
if (widget._chewieController != null) {
widget._chewieController.dispose();
}
widget._videoPlayerController =
VideoPlayerController.network(materialViewResponseData.playUrl);
widget._chewieController = ChewieController(
videoPlayerController: widget._videoPlayerController,
aspectRatio: 3 / 2,
autoPlay: true,
looping: false,
customControls: CustomControls(),
);
});
}

**Comment by cbenhagen** [comment]
You can replace the ChewieController with a new one where you set another VideoPlayerController:
https://github.com/brianegan/chewie/blob/master/example/lib/main.dart#L117-L129

Some things I noted in your code:
- You should put the controllers in the state object instead of accessing them as `widget._videoPlayerController`.
- Instead of the if statement you can just use `_videoPlayerController?.dispose()` to make sure it is only called when the controller != null.

I am closing this as there does not seem to be anything wrong or missing in `Chewie`. If it is still unclear how to use the plugin please open a question on Stack Overflow. I am happy to provide more information there.
