### ISSUE TITLE
Sample code doesn't work

### ISSUE THREAD

**Issue by daohoangson** [brianegan/chewie#224]
The player stopped working in my app so I created a new app from scratch and uses the sample code in the README. It does not work (keeps spinning).

### flutter doctor -v

```
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.14.6 18G103, locale
    en-VN)
    • Flutter version 1.9.1+hotfix.6 at /Users/xxx/repos/flutter
    • Framework revision 68587a0916 (7 weeks ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/xxx/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/xxx/Library/Android/sdk
    • Java binary at: /Users/xxx/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.5791312/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.7.2

[✓] Android Studio (version 3.5)
    • Android Studio at /Users/xxx/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.5791312/Android
      Studio.app/Contents
    • Flutter plugin version 36.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.39.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.5.1

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API
      28) (emulator)

• No issues found!
```

### pubspec.yaml

```yaml
  chewie: ^0.9.8+1
  video_player: ^0.10.2+5
```

### main.dart

```dart
import 'package:flutter/material.dart';
import 'package:chewie/chewie.dart';
import 'package:video_player/video_player.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext _) => MaterialApp(
        home: Scaffold(
          appBar: AppBar(title: Text('chewie')),
          body: Chewie(
            controller: ChewieController(
              videoPlayerController: VideoPlayerController.network(
                'https://www.w3schools.com/html/mov_bbb.mp4',
              ),
              aspectRatio: 3 / 2,
              autoPlay: true,
              looping: true,
              showControls: true,
            ),
          ),
        ),
      );
}
```

Android logcat doesn't have any useful info.

**Comment by mcxinyu** [comment]
https://flutter.github.io/assets-for-api-docs/videos/butterfly.mp4 
is 404

**Comment by daohoangson** [comment]
> is 404

That's my bad. I have updated the sample code above with `https://www.w3schools.com/html/mov_bbb.mp4` as video URL. It still doesn't work. This run I have also collected the logcat https://gist.github.com/daohoangson/d1ef32edb0a577fa482645eea5870568

**Comment by mcxinyu** [comment]
This may help you

`Source error.
E/ExoPlayerImplInternal(14928): com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to https://www.w3schools.com/html/mov_bbb.mp4
E/ExoPlayerImplInternal(14928): 	at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:281)
E/ExoPlayerImplInternal(14928): 	at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
E/ExoPlayerImplInternal(14928): 	at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:885)
E/ExoPlayerImplInternal(14928): 	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
E/ExoPlayerImplInternal(14928): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
E/ExoPlayerImplInternal(14928): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
E/ExoPlayerImplInternal(14928): 	at java.lang.Thread.run(Thread.java:818)
E/ExoPlayerImplInternal(14928): Caused by: java.net.SocketTimeoutException: failed to connect to www.w3schools.com/199.16.158.190 (port 443) after 8000ms
E/ExoPlayerImplInternal(14928): 	at libcore.io.IoBridge.connectErrno(IoBridge.java:169)
E/ExoPlayerImplInternal(14928): 	at libcore.io.IoBridge.connect(IoBridge.java:122)
E/ExoPlayerImplInternal(14928): 	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
E/ExoPlayerImplInternal(14928): 	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:452)
E/ExoPlayerImplInternal(14928): 	at java.net.Socket.connect(Socket.java:884)
E/ExoPlayerImplInternal(14928): 	at com.android.okhttp.internal.Platform.connectSocket(Platform.java:117)
E/ExoPlayerImplInternal(14928): 	at com.android.okhttp.internal.http.SocketConnector.connectRawSocket(SocketConnector.java:160)
E/ExoPlayerImplInternal(14928): 	at com.android.okhttp.internal.http.SocketConnector.connectTls(SocketConnector.java:79)
E/ExoPlayerImplInternal(14928): 	at com.android.okhttp.Connection.connect(Connection.java:143)
E/ExoPlayerImplInternal(14928): 	at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:185)
E/ExoPlayerImplInternal(14928): 	at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:128)
E/ExoPlayerImplInternal(14928): 	at com.android.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:342)
E/ExoPlayerImplInternal(14928): 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:331)
E/ExoPlayerImplInternal(14928): 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:249)
E/ExoPlayerImplInternal(14928): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:437)
E/ExoPlayerImplInternal(14928): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:114)
E/ExoPlayerImplInternal(14928): 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:89)
E/ExoPlayerImplInternal(14928): 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:25)
E/ExoPlayerImplInternal(14928): 	at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:528)
E/ExoPlayerImplInternal(14928): 	at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:444)
E/ExoPlayerImplInternal(14928): 	at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:279)
E/ExoPlayerImplInternal(14928): 	... 6 more`

**Comment by daohoangson** [comment]
> This may help you

This showed up in your logcat?! There is no such thing in mine. How did you do it? I ran `adb logcat` before running the app in VS Code.

Really appreciate the help, @mcxinyu 👍👍👍👍

**Comment by mcxinyu** [comment]
Are the logs you collected before really generated by the code running the video player?

I didn't find any words related to video playback on it.

**Comment by daohoangson** [comment]
They are generated while the app is running. The app ID is `com.example.test2019091` and I found this line:

```
10-31 13:41:26.217 24183 24214 I flutter : Observatory listening on http://127.0.0.1:37240/KA9V0m4-HdM=/
```

The timestamp matches the moment I hit run... So it must be it right?

I think the only video player related line is this one:

```
10-31 13:41:30.215 24183 24183 I ExoPlayerImpl: Init 878b1ed [ExoPlayerLib/2.9.6] [generic_x86, Android SDK built for x86, Google, 28]
```

**Comment by mcxinyu** [comment]
You can try to print some information to confirm that you have entered the corresponding widget.

**Comment by mcxinyu** [comment]
`SSL_connect error 5, errno=111`

I think it may be caused by network abnormality.

**Comment by daohoangson** [comment]
Thanks @mcxinyu for all the help. I have reset the emulator and it worked! I also tried on a device and it worked there too. I'm closing this issue now.
