### ISSUE TITLE
Does this plugin work for flutter web?

### ISSUE THREAD

**Issue by carman247** [brianegan/chewie#271]
Is this supposed to work for flutter web also?

I have managed to get it to display and play an asset video but I am getting some errors... Not sure if it's because it's in a SliverList or just because it doesn't work...

**Comment by Ahmadre** [comment]
Nope use this: https://pub.dev/packages/video_player_web or with Controls: https://pub.dev/packages/flutter_web_video_player

**Comment by brianegan** [comment]
Hey -- this plugin actually should work just fine for web, but there are a couple caveats:

  1. You must depend on Video Player 0.10.5 and higher
  2. Autoplay will not always work ,since Chrome has disabled autoplay videos when a site first starts. That's why you might see some errors, so make sure to only use `autoplay: true` when you're not on the "home page" of your app
