### ISSUE TITLE
Error bad request on iOS (Video Link m3u8 Live)

### ISSUE THREAD

**Issue by roskimlong** [brianegan/chewie#343]
When I add a link to Chewie kind of Live video, I got a problem with iOS real device...
for Android work smoothly !!
one more on AutoPlay also not work too for the latest version of Chewie :(

**Comment by Madhav008** [comment]
Hii @roskimlong  can you tell me how you play video for android

**Comment by Ahmadre** [comment]
@roskimlong chewie is only a UI-Wrapper for Flutter's `video_player` plugin.

That plug-in also depends on two crucial native plugins:
Android: Exoplayer (supports all kinds of video codecs)
IOS: No Live-Streaming support due to the used native plugin!

So because this is related to video_player and not chewie. I'll close this for now and I'd recommend to open or search for related issues in Flutter's video_player.

**Comment by roskimlong** [comment]
> Hii @roskimlong can you tell me how you play video for android

I just add VideoLink simply to Chewie plugin and it's worked well

**Comment by roskimlong** [comment]
> @roskimlong chewie is only a UI-Wrapper for Flutter's `video_player` plugin.
> 
> That plug-in also depends on two crucial native plugins:
> Android: Exoplayer (supports all kinds of video codecs)
> IOS: No Live-Streaming support due to the used native plugin!
> 
> So because this is related to video_player and not chewie. I'll close this for now and I'd recommend to open or search for related issues in Flutter's video_player.

I fixed it in the iOS video_player code !!
