### ISSUE TITLE
WakeLock upgrade

### ISSUE THREAD

**Issue by yelkamel** [brianegan/chewie#377]
Hello jsut to let you know that WakeLock can be updated.

`Because chewie 0.9.10 depends on wakelock ^0.1.2 and no versions of chewie match >0.9.10 <0.10.0, chewie ^0.9.10 requires wakelock ^0.1.2.
So, because Evolum depends on both chewie ^0.9.10 and wakelock ^0.2.0+1, version solving failed.`

**Comment by EnricoSignoriWeDoc** [comment]
Hello, I'm having the same issue...
If WakeLock is a dependency of this package the team should be more aware of changes.

**Comment by yy1300326388** [comment]
`Running "flutter pub get" in xgjapp...                          
Because app depends on chewie 0.9.10 which depends on wakelock ^0.1.2, wakelock ^0.1.2 is required.
So, because app depends on wakelock 0.2.0+1, version solving failed.

pub get failed (1; So, because app depends on wakelock 0.2.0+1, version solving failed.)
exit code 1`

**Comment by Ahmadre** [comment]
Hello guys :),

actually the past chewie contributors was very busy to new ones cam in (me and @nstrelow). We are there for you now and yes we'll definetly be more aware of dependency hell :D

**Comment by Ahmadre** [comment]
@yelkamel Fixed with: [![Version](https://img.shields.io/badge/pub-v0.10.4-blue)](https://pub.dev/packages/chewie)
