### ISSUE TITLE
some videos not loading/being shown on ios

### ISSUE THREAD

**Issue by easazade** [brianegan/chewie#490]
the problem is sometimes videos are shown on iphone and sometimes not.
when videos are not showing here is the log i get as an error:
`[VERBOSE-2:ui_dart_state.cc(199)] Unhandled Exception: PlatformException(VideoError, Failed to load video: Operation Stopped, null, null)`
and when the videos are shown the log would be something like this
`TX and TY are 0. Rotation: 0. Natural width,height: 1280.000000, 720.000000`

here is a link of a video that is now showing on iphone: 
[https://dl16.ftk.pw/user/shahab3/film/Pharaohs.War.2019.480p.BluRay.SUBFA.Film2Movie_Asia.mkv](https://dl16.ftk.pw/user/shahab3/film/Pharaohs.War.2019.480p.BluRay.SUBFA.Film2Movie_Asia.mkv)
here is a link that works fine
  [https://flutter.github.io/assets-for-api-docs/assets/videos/bee.mp4](https://flutter.github.io/assets-for-api-docs/assets/videos/bee.mp4)

**Comment by Ahmadre** [comment]
This issue is not because of chewie: Chewie is just a wrapper and the UI-part here.

Please file an issue in video_player plugin, thanks :)

Furthermore: we constantly update the video_player dependency and we recognized, that some regressions have been fixed. Please update your chewie to 1.2.1 and try again or file an issue on video_player.

Thx
